"""ADV — Advanced Routing Protocols (40)."""

SRC = "ANDM technical domains 2026-07 (Doyle / MPLS Fundamentals / RFC 7938)"

def q(n, tags, question, options, explanation, correct=0):
    return {
        "id": f"ADV-{n:03d}",
        "module": "ADV",
        "difficulty": "interview",
        "tags": tags,
        "source": SRC,
        "question": question,
        "options": options,
        "correctIndex": correct,
        "explanation": explanation,
    }

QUESTIONS = [
q(1, ["bgp", "decision"],
 "A peer claims BGP selects the path with the fewest hops. Your correction:",
 ["BGP is policy-driven; the decision process uses attributes such as Weight, Local Preference, AS-path length, Origin, MED, then IGP cost—not raw hop count",
  "BGP always mirrors OSPF cost",
  "BGP only encrypts control packets",
  "BGP ignores all attributes except MED"],
 "Doyle Vol II: BGP decision process literacy beats 'shortest path' folklore."),

q(2, ["bgp", "ibgp"],
 "Why do large ASes need route reflectors or confederations for iBGP?",
 ["Full-mesh iBGP does not re-advertise iBGP-learned routes, so scale needs RR/confeds (or add-path designs) to distribute paths without an N² mesh",
  "iBGP cannot carry IPv4 prefixes",
  "OSPF forbids more than two BGP speakers",
  "Route reflectors replace TCP"],
 "iBGP split-horizon drives RR/confederation architecture."),

q(3, ["bgp", "ebgp"],
 "In a Clos fabric built per RFC 7938, why is eBGP often preferred as the underlay routing protocol?",
 ["eBGP gives clear AS boundaries, simple policy knobs, and scales with ECMP without flooding a full IGP topology into every leaf",
  "eBGP cannot do multipath",
  "RFC 7938 bans BGP in DCs",
  "eBGP only works over the public Internet"],
 "Modern DC: eBGP Clos underlay pattern."),

q(4, ["bgp", "attributes"],
 "Local Preference vs AS-path for outbound path selection inside one AS:",
 ["Local Preference is local to the AS and preferred earlier in the decision process; AS-path length compares after Local Pref (among other steps)",
  "AS-path always beats Local Pref",
  "MED always beats Local Pref",
  "They are identical knobs"],
 "Order of BGP decision process matters for ops."),

q(5, ["bgp", "med"],
 "When is MED most useful?",
 ["Influencing which entry point a neighboring AS prefers into your AS when multiple links exist—MED is typically compared between paths from the same neighboring AS",
  "Encrypting BGP sessions",
  "Replacing OSPF areas",
  "Setting IPv6 next-hops only"],
 "MED is an inter-AS ingress preference signal with caveats."),

q(6, ["bgp", "communities"],
 "A team wants operators to tag routes for later filtering without changing AS-path. Best tool:",
 ["BGP communities (or large/extended communities) as opaque tags for policy",
  "Increasing OSPF cost only",
  "Shortening TTL",
  "Disabling TCP MD5"],
 "Communities are the workhorse for scalable BGP policy."),

q(7, ["bgp", "fsm"],
 "BGP session stuck in Active/Connect—most likely class of issue?",
 ["TCP session / reachability / ACL / wrong peer IP or ASN—not a finished OPEN exchange",
  "SPF calculation loop",
  "Label stack exhaustion",
  "DNS recursive failure only"],
 "FSM literacy: Idle/Connect/Active/OpenSent/OpenConfirm/Established."),

q(8, ["bgp", "next-hop"],
 "iBGP advertises a prefix but the next-hop is unreachable. Symptom:",
 ["Route may be in RIB as invalid/hidden until next-hop is resolvable via IGP/static—or next-hop-self is applied on the edge",
  "BGP automatically rewrites Ethernet MACs",
  "MPLS deletes the prefix",
  "OSPF Area 0 fixes it automatically"],
 "Next-hop reachability is a classic Dive Deep trap."),

q(9, ["bgp", "scale"],
 "Update-group / peer-group style scaling helps because:",
 ["Speakers can format and replicate updates efficiently across peers that share the same outbound policy",
  "They remove the need for TCP",
  "They replace TCAM",
  "They disable route reflection"],
 "Control-plane CPU and formatting cost at scale."),

q(10, ["bgp", "graceful"],
 "Graceful Restart / long-lived graceful restart aims to:",
 ["Preserve forwarding during control-plane restart so data plane can keep forwarding while sessions re-establish",
  "Delete all FIB entries instantly",
  "Convert BGP into OSPF",
  "Disable BFD permanently"],
 "Separate control plane restart from forwarding continuity."),

q(11, ["ospf", "areas"],
 "Why does OSPF use areas?",
 ["To bound LSDB size and SPF blast radius—ABRs summarize/filter between areas while Area 0 is the backbone",
  "To encrypt every LSA",
  "To replace BGP ASNs",
  "Areas only exist for IPv6"],
 "Doyle Vol I: hierarchical OSPF design."),

q(12, ["ospf", "lsa"],
 "Type 1 vs Type 2 LSA roles:",
 ["Type 1 (Router) describes a router's links; Type 2 (Network) describes a multi-access network and attached routers (DR-originated)",
  "Type 2 replaces BGP UPDATE",
  "Type 1 is only for stubs",
  "They are identical"],
 "LSA type literacy for adjacency/topology debugging."),

q(13, ["ospf", "lsa"],
 "Type 3 vs Type 5 LSA:",
 ["Type 3 (Summary) is ABR-originated inter-area; Type 5 (External) is ASBR-originated redistributed external routes (Type 4 finds the ASBR)",
  "Type 5 is only intra-area",
  "Type 3 is MPLS labels",
  "Type 5 cannot leave Area 0"],
 "External vs summary is a frequent exam/interview discriminator."),

q(14, ["ospf", "adjacency"],
 "Two OSPF routers on a LAN form 2-Way but not Full. Likely focus:",
 ["DR/BDR election and adjacency only to DR/BDR on broadcast—or MTU/area/network-type/hello mismatch blocking FULL",
  "BGP community mismatch",
  "Missing MPLS LDP",
  "Cloud WAN segment map"],
 "Neighbor state machine: Down→Init→2-Way→ExStart→Exchange→Loading→Full."),

q(15, ["ospf", "spf"],
 "An engineer proposes running OSPF as a single area across a huge DC. Risk:",
 ["LSDB and SPF scale poorly—churn floods everywhere; hierarchy or alternate design (e.g. eBGP Clos) is usually safer",
  "OSPF cannot do ECMP",
  "Single area forbids BFD",
  "SPF only works with MPLS"],
 "Capacity of the control plane is a manager concern."),

q(16, ["ospf", "stub"],
 "Stub / totally stubby / NSSA intent:",
 ["Reduce external (and optionally summary) LSAs in an area, injecting a default instead—NSSA allows limited external origination",
  "Force every prefix into Type 5",
  "Disable Area 0",
  "Replace ABR with RR"],
 "Area types trade reachability detail for scale."),

q(17, ["ospf", "cost"],
 "OSPF path selection basics:",
 ["Intra-area paths preferred over inter-area; lowest cost wins; equal-cost paths can ECMP",
  "AS-path length decides OSPF",
  "Local Pref is an OSPF LSA",
  "OSPF ignores interface cost"],
 "Contrast with BGP policy model."),

q(18, ["ospf", "redistribute"],
 "Redistributing BGP into OSPF without filters—manager concern:",
 ["Control-plane and LSDB explosion; suboptimal paths; feedback loops—need careful filtering, tags, and metrics",
  "It always improves convergence",
  "OSPF automatically aggregates Internet table safely",
  "No risk if Area 0 exists"],
 "Mutual redistribution is a classic blast-radius topic."),

q(19, ["ospf", "network-type"],
 "Point-to-point vs broadcast OSPF network types matter because:",
 ["They change adjacency model (DR or not), timers expectations, and how links appear in the LSDB",
  "They change TCP window size only",
  "They enable IPsec",
  "They set BGP MED"],
 "Mismatched network types → stubborn adjacency issues."),

q(20, ["ospf", "v2v3"],
 "OSPFv2 vs OSPFv3 high-level difference:",
 ["OSPFv3 is redesigned for IPv6 (and can carry IPv4 with extensions); addressing/flooding details differ from OSPFv2's IPv4-centric design",
  "OSPFv3 removes the concept of areas",
  "OSPFv2 supports only MPLS",
  "They use identical packet formats"],
 "Know they are related but not drop-in identical."),

q(21, ["isis", "levels"],
 "IS-IS Level-1 vs Level-2:",
 ["L1 is intra-area routing; L2 is backbone/inter-area; L1-L2 routers attach areas to the L2 backbone (mental model analogous to OSPF areas)",
  "L1 is only for BGP",
  "L2 forbids TLVs",
  "Levels replace ASNs"],
 "Doyle Vol I IS-IS hierarchy."),

q(22, ["isis", "tlv"],
 "Why is IS-IS often described as TLV-extensible?",
 ["Protocol data uses Type-Length-Value encoding, easing new address families and capabilities without redesigning the core",
  "TLV means TCP Layer Virtualization",
  "IS-IS cannot carry IPv6",
  "TLVs replace SPF"],
 "Extensibility is a key IS-IS selling point historically."),

q(23, ["isis", "vs-ospf"],
 "Practical reason some operators prefer IS-IS over OSPF in SP/DC cores:",
 ["Runs over L2 (not IP), historically strong multi-AF/TLV story and operational familiarity—tradeoffs, not universal superiority",
  "IS-IS cannot blackhole",
  "OSPF cannot ECMP",
  "IS-IS requires MPLS"],
 "Interview answer: tradeoffs + ops culture, not dogma."),

q(24, ["isis", "net"],
 "An IS-IS NET address encodes:",
 ["Area and system ID (NSAP/NET format)—misconfigured area/system ID prevents adjacency",
  "BGP community lists",
  "MPLS label ranges only",
  "AWS VPC CIDRs"],
 "Addressing mistakes are common IS-IS breaks."),

q(25, ["isis", "metric"],
 "Wide metrics in IS-IS matter because:",
 ["Narrow metrics are too coarse for modern TE/ECMP designs; wide metrics give finer cost control",
  "Wide metrics disable SPF",
  "Metrics replace BFD",
  "Only L1 uses metrics"],
 "Cost granularity for traffic engineering style ops."),

q(26, ["isis", "overload"],
 "Setting the IS-IS overload bit is used to:",
 ["Signal that the node should be avoided for transit during maintenance/boot until ready",
  "Increase BGP Local Pref",
  "Flush all MPLS labels permanently",
  "Convert L1 to L2"],
 "Maintenance hygiene analogous to max-metric tricks."),

q(27, ["isis", "adjacency"],
 "IS-IS adjacency fails—checklist includes:",
 ["Level mismatch, NET/area mismatch, MTU, authentication, circuit type, and whether both sides expect point-to-point vs broadcast",
  "Only AS-path filters",
  "Only Security Group rules in AWS",
  "DNS TTLs"],
 "Same debugging discipline as OSPF, different knobs."),

q(28, ["isis", "attach"],
 "L1 router installs a default toward L1-L2 because:",
 ["Attached bit / default origination from L1-L2 provides inter-area exit without full L2 topology in L1",
  "BGP RR reflects defaults into IS-IS automatically",
  "MPLS LDP injects defaults",
  "OSPF Type 5 is required"],
 "Hierarchy leak of default, not full Internet."),

q(29, ["mpls", "labels"],
 "What does an MPLS label primarily do in the data plane?",
 ["Indexes a short label-switched forwarding decision (LFIB) so core LSRs can forward without IP lookup on every hop",
  "Encrypts the IP payload",
  "Replaces TCP sequence numbers",
  "Stores BGP communities"],
 "MPLS Fundamentals: label switching idea."),

q(30, ["mpls", "stack"],
 "A packet with a label stack arrives; the LSR typically:",
 ["Looks up the top label and may swap/push/pop per LFIB—PHP often pops the penultimate label",
  "Always strips all labels and floods L2",
  "Converts labels into OSPF costs",
  "Requires IPsec before any forward"],
 "Push/swap/pop + penultimate hop popping concept."),

q(31, ["mpls", "ldp"],
 "LDP's role:",
 ["Distribute label bindings for FECs so LSPs can be established for IGP-learned prefixes (common LDP+IGP model)",
  "Replace BGP entirely",
  "Encrypt WAN links",
  "Allocate VPC CIDRs"],
 "Control plane for labels alongside IGP."),

q(32, ["mpls", "rsvp-te"],
 "RSVP-TE is used when you need:",
 ["Traffic-engineered LSPs with bandwidth/constraint routing—not just follow-IGP LDP paths",
  "Faster ARP",
  "YAML inventory parsing",
  "Security Group evaluation"],
 "TE vs vanilla shortest-path label distribution."),

q(33, ["mpls", "l3vpn"],
 "In MPLS L3VPN, VRF + RD + RT divide labor as:",
 ["VRF separates tables; RD makes prefixes unique in BGP; RTs control which VPNs import/export which routes",
  "RD encrypts packets; RT is a VLAN ID",
  "VRF replaces the underlay IGP",
  "RT is only for LDP hello"],
 "Core L3VPN mental model for interviews."),

q(34, ["mpls", "vpnv4"],
 "VPNv4 BGP carries:",
 ["Labeled VPN prefixes (RD:prefix) so PEs can exchange customer routes across a shared MPLS core",
  "Only IS-IS TLVs",
  "Only MAC addresses",
  "CloudFormation templates"],
 "MP-BGP as VPN control plane."),

q(35, ["mpls", "p-pe"],
 "P vs PE router roles:",
 ["PE (Provider Edge) maintains VRFs/customer adjacency; P (Provider) typically switches labels in the core without customer routes",
  "P routers store all Internet + VPN tables",
  "PE never runs BGP",
  "P routers terminate customer CE sessions"],
 "Separation keeps core scalable."),

q(36, ["mpls", "php"],
 "Penultimate hop popping (PHP) exists to:",
 ["Let the egress PE avoid an unnecessary label lookup by receiving an IP (or inner) packet from the penultimate LSR",
  "Remove the need for LDP",
  "Force RSVP on every link",
  "Disable ECMP"],
 "Classic MPLS optimization detail."),

q(37, ["bfd", "convergence"],
 "BFD paired with BGP/OSPF/IS-IS helps because:",
 ["Sub-second forwarding-plane liveliness detection can trigger faster session teardown than hello timers alone",
  "BFD replaces SPF",
  "BFD allocates labels",
  "BFD is only for Wi-Fi"],
 "Fast failure detection cross-cutting control planes."),

q(38, ["ecmp", "fib"],
 "ECMP in the FIB means:",
 ["Multiple equal-cost next hops installed; hashing spreads flows—watch polarization and unequal member health",
  "One next hop always wins randomly per packet with no hash",
  "ECMP disables BGP",
  "ECMP requires MPLS L3VPN"],
 "Underlay scale tool with operational caveats."),

q(39, ["sr", "evpn"],
 "Segment Routing vs classic LDP—manager-level distinction:",
 ["SR encodes the path/segments in the packet (often MPLS or IPv6 SID) reducing per-flow state in the core versus distributed LDP bindings—EVPN is a separate overlay control plane for L2/L3 VPN services",
  "SR deletes the need for an IGP",
  "EVPN replaces TCP",
  "SR and EVPN are identical protocols"],
 "Light awareness only—don't over-claim expertise."),

q(40, ["redistribute", "policy"],
 "Mutually redistributing OSPF ↔ BGP without tags/filters—failure mode:",
 ["Route feedback loops, suboptimal paths, and control-plane overload—use tags, prefer points, and tight prefix filters",
  "Guaranteed optimal global routing",
  "Automatic RD/RT assignment",
  "IS-IS levels self-heal it"],
 "Cross-protocol policy is where outages hide."),
]
